name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install  pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test en pytest
      run: pytest